# Model configurations

models:
  # GPT-2 models (HuggingFace)
  gpt2:
    type: huggingface
    model_id: gpt2
    device: auto

  gpt2-medium:
    type: huggingface
    model_id: gpt2-medium
    device: auto

  gpt2-large:
    type: huggingface
    model_id: gpt2-large
    device: auto
    load_in_8bit: false  # Set to true if low on VRAM

  gpt2-xl:
    type: huggingface
    model_id: gpt2-xl
    device: auto
    load_in_8bit: false

  # OpenAI models
  gpt-3.5-turbo-instruct:
    type: openai
    model_id: gpt-3.5-turbo-instruct
    cost_per_1k: 0.002

  gpt-4:
    type: openai
    model_id: gpt-4
    cost_per_1k: 0.04

  gpt-4-turbo:
    type: openai
    model_id: gpt-4-turbo-preview
    cost_per_1k: 0.02

  gpt-5:
    type: openai
    model_id: gpt-5
    cost_per_1k: 0.00125  # $1.25/1M input, $10/1M output (averaging)

  # Anthropic models
  claude-3-5-sonnet-20241022:
    type: anthropic
    model_id: claude-3-5-sonnet-20241022
    cost_per_1k: 0.003

  claude-3-opus:
    type: anthropic
    model_id: claude-3-opus-20240229
    cost_per_1k: 0.015

  claude-3-haiku:
    type: anthropic
    model_id: claude-3-haiku-20240307
    cost_per_1k: 0.00025

  claude-4-opus:
    type: anthropic
    model_id: claude-opus-4-1-20250805
    cost_per_1k: 0.015  # $15/1M input, $75/1M output (averaging)

  # Llama models (HuggingFace)
  llama3-8b:
    type: huggingface
    model_id: meta-llama/Meta-Llama-3-8B-Instruct
    device: auto
    load_in_8bit: true  # Recommended for consumer GPUs

  llama3-70b:
    type: huggingface
    model_id: meta-llama/Llama-3.3-70B-Instruct  # December 2024 release
    device: auto
    load_in_8bit: true  # Required for most GPUs

  # Qwen models (Alibaba) - September 2024 release
  qwen2.5-7b:
    type: huggingface
    model_id: Qwen/Qwen2.5-7B-Instruct
    device: auto
    load_in_8bit: false

  qwen2.5-72b:
    type: huggingface
    model_id: Qwen/Qwen2.5-72B-Instruct  # September 2024 release
    device: auto
    load_in_8bit: true  # Requires 80GB+ VRAM without quantization

  # Mistral models
  mistral-7b:
    type: huggingface
    model_id: mistralai/Mistral-7B-Instruct-v0.3
    device: auto
    load_in_8bit: false

  mistral-small-3-24b:
    type: huggingface
    model_id: mistralai/Mistral-Small-24B-Instruct-2501  # January 2025 release
    device: auto
    load_in_8bit: true

  mixtral-8x7b:
    type: huggingface
    model_id: mistralai/Mixtral-8x7B-Instruct-v0.1  # MoE architecture
    device: auto
    load_in_8bit: true  # MoE architecture, efficient but still large

  # DeepSeek models
  deepseek-7b:
    type: huggingface
    model_id: deepseek-ai/deepseek-llm-7b-chat
    device: auto
    load_in_8bit: false

  deepseek-67b:
    type: huggingface
    model_id: deepseek-ai/deepseek-llm-67b-chat
    device: auto
    load_in_8bit: true

# Cost tracking settings
cost_tracking:
  track_costs: true
  warn_at_cost: 10.0  # Warn when total cost exceeds this
  stop_at_cost: 50.0  # Stop experiments when total cost exceeds this