'# Note': WebText-style prompts extracted from high-quality text sources
'# Source': Similar to prompts used in Holtzman et al. 2019
'# Prompt length': 10-40 tokens as in the original paper
webtext_prompts:
- Neuroscientists studying the human brain have made remarkable discoveries about
  how memories are formed and stored.
- The rise of artificial intelligence in healthcare has begun
- The mathematics behind modern cryptography relies on problems that are easy to verify
  but computationally difficult to solve. As quantum computers become more powerful
- Archaeological excavations in Turkey have uncovered what may be the world's oldest
- Climate scientists have been tracking the unprecedented rate of ice melt in
- Urban planners are increasingly turning to data science and artificial
- Linguists studying endangered languages estimate that half of the world's 7,000
  languages will disappear within the next century. Each language that vanishes takes
  with it
- The global supply chain crisis that emerged during the pandemic has forced companies
  to reconsider their manufacturing
- The discovery of gravitational waves has opened an entirely
- In the depths of the Amazon rainforest, researchers have discovered a complex network
  of ancient settlements connected by road systems. These pre-Columbian civilizations
  were far more sophisticated
- Astronomers have detected mysterious radio signals from distant galaxies that repeat
  in predictable patterns. These fast radio bursts release as much energy in milliseconds
- The discovery of CRISPR gene-editing technology has opened unprecedented possibilities
  for treating genetic diseases. Scientists can now precisely modify DNA sequences
- The human microbiome, consisting of trillions of bacteria living in and
- The rapid evolution of electric vehicle technology has pushed traditional automakers
  to completely reimagine their business models. Battery costs have fallen by more
  than 80 percent
- Marine biologists exploring the deep ocean have discovered ecosystems thriving in
  complete darkness around hydrothermal vents. These unique environments host species
- Coral reefs around the world are experiencing unprecedented bleaching events due
- The development of quantum computing has accelerated rapidly in recent years, with
  major technology companies investing billions of dollars in research. These powerful
  machines promise to revolutionize fields from
- The development of mRNA vaccines during the COVID-19 pandemic has revolutionized
  our approach to preventing infectious diseases. This technology, decades in the
  making
- Renewable energy sources have become increasingly cost-competitive with fossil fuels,
  leading to a
- The James Webb Space Telescope has captured images of galaxies that formed just
  a few hundred
'# For experiments': ''
default_prompts:
- Neuroscientists studying the human brain have made remarkable discoveries about
  how memories are formed and stored.
- The rise of artificial intelligence in healthcare has begun
- The mathematics behind modern cryptography relies on problems that are easy to verify
  but computationally difficult to solve. As quantum computers become more powerful
- Archaeological excavations in Turkey have uncovered what may be the world's oldest
- Climate scientists have been tracking the unprecedented rate of ice melt in
- Urban planners are increasingly turning to data science and artificial
- Linguists studying endangered languages estimate that half of the world's 7,000
  languages will disappear within the next century. Each language that vanishes takes
  with it
- The global supply chain crisis that emerged during the pandemic has forced companies
  to reconsider their manufacturing
- The discovery of gravitational waves has opened an entirely
- In the depths of the Amazon rainforest, researchers have discovered a complex network
  of ancient settlements connected by road systems. These pre-Columbian civilizations
  were far more sophisticated
- Astronomers have detected mysterious radio signals from distant galaxies that repeat
  in predictable patterns. These fast radio bursts release as much energy in milliseconds
- The discovery of CRISPR gene-editing technology has opened unprecedented possibilities
  for treating genetic diseases. Scientists can now precisely modify DNA sequences
- The human microbiome, consisting of trillions of bacteria living in and
- The rapid evolution of electric vehicle technology has pushed traditional automakers
  to completely reimagine their business models. Battery costs have fallen by more
  than 80 percent
- Marine biologists exploring the deep ocean have discovered ecosystems thriving in
  complete darkness around hydrothermal vents. These unique environments host species
- Coral reefs around the world are experiencing unprecedented bleaching events due
- The development of quantum computing has accelerated rapidly in recent years, with
  major technology companies investing billions of dollars in research. These powerful
  machines promise to revolutionize fields from
- The development of mRNA vaccines during the COVID-19 pandemic has revolutionized
  our approach to preventing infectious diseases. This technology, decades in the
  making
- Renewable energy sources have become increasingly cost-competitive with fossil fuels,
  leading to a
- The James Webb Space Telescope has captured images of galaxies that formed just
  a few hundred
'# Task-specific prompts remain the same': ''
creative_prompts:
- Once upon a time in a land far away
- The old mansion stood at the end of the street
- She opened the mysterious letter and gasped
factual_prompts:
- The capital of France is
- Water boils at a temperature of
- The speed of light in vacuum is approximately
prompt_sets:
  degeneration: webtext_prompts
  perplexity: webtext_prompts
  tail_analysis: webtext_prompts
